# Generated by Django 6.1.1 on 2026-10-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-created_at',), 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ('-created_at',), 'verbose_name': 'Quiz attempt', 'verbose_name_plural': 'Quiz attempts'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time in seconds'),
        ),
    ]
